version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/job-portal-app
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
